apiVersion: v1
kind: Pod
metadata:
  name: busyboxapp
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sleep", "360"] 
  initContainers:
  - name: init-busybox
    image: busybox:latest
    command: ["sh", "-c", "echo 'Initializing BusyBox Pod...' && sleep 10"]
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: NoSchedule
