apiVersion: v1
kind: Pod
metadata:
  name: nginxapp
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  nodeSelector:
    gpu: "false"
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: NoSchedule

  
